<?php

use \Drupal\Core\Site\Settings;

/**
 * Implements hook_link_alter().
 */
function group_purl_link_alter(&$variables) {
  /** @var \Drupal\Core\Url $url */
  $options = &$variables['options'];
  if (isset($options['purl_context']) && !$options['absolute']) {

    $modifier = $options['purl_context']['modifier'];
    if (strpos($modifier, '.') !== FALSE) {
        // domain, has a dot
        $host = $modifier;
      }
      else {
        // path
        $host = Settings::get('purl_base_domain') . '/' . $modifier;
      }

    $linkhost = isset($options['purl_context']['modifier'])
      ? $host
      : Settings::get('purl_base_domain');
    $host = \Drupal::service('router.request_context')->getHost();
    if ($linkhost != $host) {
      $options['host'] = $linkhost;
      $options['absolute'] = TRUE;
    }

  }

}